### ISSUE TITLE
error in "make runtest" for the current caffe-segnet

### ISSUE THREAD

**Issue by amiltonwong** [alexgkendall/caffe-segnet#7] opened 2015-11-10 17:48 UTC
Hi, @alexgkendall ,
I had compiled the current caffe-segnet again.
"make all" and "make test" passed, but came across error in "make runtest" 
The details can be viewed here:
https://goo.gl/vwW8GT

Although I can run "/SegNet/caffe-segnet/build/tools/caffe train -gpu 0 -solver /SegNet/Models/segnet_solver.prototxt" successfully.

Could this error be ignored or should be fixed?

Thanks~
Milton

**Comment by alexgkendall** [comment] 2015-11-11 10:07
Hi @amiltonwong ,

Thank you for spotting this! This was caused by an extra dimensionality check I placed in the class balancing code which my test case wasn't build to handle. I've pushed a fix of the test case to the repo. It should pass all tests now.

Alex

**Closed as completed** 2015-11-11 10:08 UTC
